# Generated by Django 5.0 on 2023-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.CharField(choices=[('t', 'Completed'), ('p', 'Pending')], max_length=20),
        ),
    ]
